version: "3.2"

services:
  taller:
    image: taller-db-service
    build:
      context: .
    command: uvicorn app.main:app --reload --workers 1 --host 0.0.0.0 --port 8000
    volumes:
      - ./:/usr/src/app/
    ports:
      - 7081:8000
    environment:
      - TESTING=0
      - WEB_APP_VERSION=0.0.1
      - WEB_APP_TITLE=taller
      - WEB_APP_DESCRIPTION=This is a microservice to ing web final workshop
      - DATABASE_DEV_URL=postgres://postgres:postgres@taller-db:5432/taller_dev
      - DATABASE_PROD_URL=postgres://postgres:postgres@taller-db:5432/taller_prod
      - DATABASE_TEST_URL=postgres://postgres:postgres@taller-db:5432/taller_test
      - ENVIROMENT=dev # dev or prod
    networks:
      - taller

  taller-db:
    image: taller-db
    build:
      context: ./db
      dockerfile: Dockerfile
    expose:
      - 5432
    ports:
      - "5434:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - db_taller:/var/lib/postgresql/data
    networks:
      - taller


volumes:
  db_taller:
    external: true

networks:
  taller:
    external: true
