version: "3.2"

services:
  cft:
    image: gazelle-br-cft
    build:
      context: .
    command: uvicorn app.main:app --reload --workers 1 --host 0.0.0.0 --port 8000
    ports:
      - 8051:8000
    environment:
      - TESTING=0
      - WEB_APP_VERSION=0.0.1
      - WEB_APP_TITLE=gazelle-br-cft
      - WEB_APP_DESCRIPTION=This is a microservice to evaluate the CFT business rules
      - DATABASE_DEV_URL=postgres://postgres:postgres@gazelle-db:5432/gazelle_dev
      - DATABASE_PROD_URL=postgres://postgres:postgres@gazelle-db:5432/gazelle_prod
      - DATABASE_TEST_URL=postgres://postgres:postgres@gazelle-db:5432/gazelle_test
      - ENVIROMENT=dev # dev or prod
      - DEFAULT_EXPIRE_TIME=3600
    networks:
      - gazelle

  gazelle-db:
    image: gazelle-db
    build:
      context: ./.github/db
      dockerfile: Dockerfile
    expose:
      - 5432
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    networks:
      - gazelle

networks:
  gazelle:
    external: true