version: "3.2"

services:
  taller:
    image: taller-db-service
    build:
      context: .
    command: uvicorn app.main:app --reload --workers 1 --host 0.0.0.0 --port 8000
    volumes:
      - ./:/usr/src/app/
    ports:
      - 7071:8000
      - 10001:10001
    env_file:
      - .env
    networks:
      - taller

  taller-db:
    image: taller-db
    build:
      context: ./db
      dockerfile: Dockerfile
    expose:
      - 5432
    ports:
      - "5434:5432"
    env_file:
      - .db.env
    volumes:
      - db_taller:/var/lib/postgresql/data
    networks:
      - taller


volumes:
  db_taller:
    external: true

networks:
  taller:
    external: true
