version: "3.2"

services:
  taller:
    image: taller-db-service
    build:
      context: .
    command: uvicorn app.main:app --reload --workers 1 --host 0.0.0.0 --port 8000
    ports:
      - 8051:8000
    environment:
      - TESTING=0
      - WEB_APP_VERSION=0.0.1
      - WEB_APP_TITLE=taller
      - WEB_APP_DESCRIPTION=This is a microservice to ing web final workshop
      - DATABASE_TEST_URL=postgres://postgres:postgres@taller-db:5432/taller_test
      - ENVIROMENT=dev
    networks:
      - taller

  taller-db:
    image: taller-db
    build:
      context: ./.github/db
      dockerfile: Dockerfile
    expose:
      - 5432
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    networks:
      - taller

networks:
  taller:
    external: true
